let handler = m => m

handler.before = function (m) {
  let user = global.DATABASE.data.users[m.sender]
        let role = (user.level <= 2) ? 'Novato ㋡'
          : ((user.level >= 2) && (user.level <= 4)) ? 'Principiante Grado 1 ⚊¹'
          : ((user.level >= 4) && (user.level <= 6)) ? 'Principiante Grado 2 ⚊²'
          : ((user.level >= 6) && (user.level <= 8)) ? 'Principiante Grado  3 ⚊³'
          : ((user.level >= 8) && (user.level <= 10)) ? 'Principiante Grado  4 ⚊⁴'
          : ((user.level >= 10) && (user.level <= 20)) ? 'Grado Privado 1 ⚌¹'
          : ((user.level >= 20) && (user.level <= 30)) ? 'Grado Privado 2 ⚌²'
          : ((user.level >= 30) && (user.level <= 40)) ? 'Grado Privado 3 ⚌³'
          : ((user.level >= 40) && (user.level <= 50)) ? 'Grado Privado 4 ⚌⁴'
          : ((user.level >= 50) && (user.level <= 60)) ? 'Grado Privado 5 ⚌⁵'
          : ((user.level >= 60) && (user.level <= 70)) ? 'Cabo Grado 1 ☰¹' 
          : ((user.level >= 70) && (user.level <= 80)) ? 'Cabo Grado 2 ☰²' 
          : ((user.level >= 80) && (user.level <= 90)) ? 'Cabo Grado 3 ☰³' 
          : ((user.level >= 90) && (user.level <= 100)) ? 'Cabo Grado 4 ☰⁴' 
          : ((user.level >= 100) && (user.level <= 110)) ? 'Cabo Grado 5 ☰⁵'
          : ((user.level >= 110) && (user.level <= 120)) ? 'Sargento Grado 1 ≣¹'
          : ((user.level >= 120) && (user.level <= 130)) ? 'Sargento Grado 2 ≣²'
          : ((user.level >= 130) && (user.level <= 140)) ? 'Sargento Grado 3 ≣³'
          : ((user.level >= 140) && (user.level <= 150)) ? 'Sargento Grado 4 ≣⁴'
          : ((user.level >= 150) && (user.level <= 160)) ? 'Sargento Grado 5 ≣⁵' 
          : ((user.level >= 160) && (user.level <= 170)) ? 'Grado del personal 1 ﹀¹' 
          : ((user.level >= 170) && (user.level <= 180)) ? 'Grado del personal 2 ﹀²' 
          : ((user.level >= 180) && (user.level <= 190)) ? 'Grado del personal 3 ﹀³' 
          : ((user.level >= 190) && (user.level <= 200)) ? 'Grado del personal 4 ﹀⁴' 
          : ((user.level >= 200) && (user.level <= 210)) ? 'Grado del personal 5 ﹀⁵' 
          : ((user.level >= 210) && (user.level <= 220)) ? 'Grado de sargento 1 ︾¹'
          : ((user.level >= 220) && (user.level <= 230)) ? 'Grado de sargento 2 ︾²'
          : ((user.level >= 230) && (user.level <= 240)) ? 'Grado de sargento 3 ︾³'
          : ((user.level >= 240) && (user.level <= 250)) ? 'Grado de sargento 4 ︾⁴'
          : ((user.level >= 250) && (user.level <= 260)) ? 'Grado de sargento 5 ︾⁵'
          : ((user.level >= 260) && (user.level <= 270)) ? '2do Teniente Grado 1 ♢¹'
          : ((user.level >= 270) && (user.level <= 280)) ? '2do Teniente Grado 2 ♢²'  
          : ((user.level >= 280) && (user.level <= 290)) ? '2do Teniente Grado 3 ♢³' 
          : ((user.level >= 290) && (user.level <= 300)) ? '2do Teniente Grado 4 ♢⁴' 
          : ((user.level >= 300) && (user.level <= 310)) ? '2do Teniente Grado 5 ♢⁵'
          : ((user.level >= 310) && (user.level <= 320)) ? '1er Teniente Grado 1 ♢♢¹'
          : ((user.level >= 320) && (user.level <= 330)) ? '1er Teniente Grado 2 ♢♢²'
          : ((user.level >= 330) && (user.level <= 340)) ? '1er Teniente Grado 3 ♢♢³'
          : ((user.level >= 340) && (user.level <= 350)) ? '1er Teniente Grado 4 ♢♢⁴'
          : ((user.level >= 350) && (user.level <= 360)) ? '1er Teniente Grado 5 ♢♢⁵'
          : ((user.level >= 360) && (user.level <= 370)) ? 'Grado Mayor 1 ✷¹'
          : ((user.level >= 370) && (user.level <= 380)) ? 'Grado Mayor 2 ✷²'
          : ((user.level >= 380) && (user.level <= 390)) ? 'Grado Mayor 3 ✷³'
          : ((user.level >= 390) && (user.level <= 400)) ? 'Grado Mayor 4 ✷⁴'
          : ((user.level >= 400) && (user.level <= 410)) ? 'Grado Mayor 5 ✷⁵'
          : ((user.level >= 410) && (user.level <= 420)) ? 'Grado Coronel 1 ✷✷¹'
          : ((user.level >= 420) && (user.level <= 430)) ? 'Grado Coronel 2 ✷✷²'
          : ((user.level >= 430) && (user.level <= 440)) ? 'Grado Coronel 3 ✷✷³'
          : ((user.level >= 440) && (user.level <= 450)) ? 'Grado Coronel 4 ✷✷⁴'
          : ((user.level >= 450) && (user.level <= 460)) ? 'Grado Coronel 5 ✷✷⁵'
          : ((user.level >= 460) && (user.level <= 470)) ? 'Brigadier temprano ✰'
          : ((user.level >= 470) && (user.level <= 480)) ? 'Brigadier plata ✩'
          : ((user.level >= 480) && (user.level <= 490)) ? 'Brigadier oro ✯' 
          : ((user.level >= 490) && (user.level <= 500)) ? 'Brigadier Platino ✬'
          : ((user.level >= 500) && (user.level <= 600)) ? 'Brigadier Diamante ✪'
          : ((user.level >= 600) && (user.level <= 700)) ? 'Legendario 忍'
          : ((user.level >= 700) && (user.level <= 800)) ? 'Legendario 忍忍'
          : ((user.level >= 800) && (user.level <= 900)) ? 'Legendario 忍忍忍'
          : ((user.level >= 900) && (user.level <= 1000)) ? 'Legendario 忍忍忍忍'
          : 'Master 숒 × Legendary 숒'
  user.role = role
  return true
}

module.exports = handler
